### ISSUE TITLE
Implement Modular CSS for Better Organization

### ISSUE THREAD

**Issue by connect-bilal** [Abdullah-dev1/react-portfoilo#3]
To improve scalability and maintainability, we should refactor the CSS to use a modular approach. This means splitting styles into smaller, reusable CSS files and importing them in relevant components.

Here’s a sample GitHub issue template for implementing modular CSS:

**Description**:
Refactor the CSS to use a modular approach. This means splitting styles into smaller, reusable CSS files and importing them in relevant components.

### **Why It's Useful**:
- **Scalability**: Easier to manage as the project grows.
- **Reusability**: Allows components to have self-contained styles.
- **Maintainability**: Makes it simpler to update or modify styles for individual components without affecting others.
- **Isolation**: Prevents style leaks and conflicts between components.

### **How to Convert Current CSS to Modular CSS**:
1. **Identify Components**: Break down the application into smaller, reusable components (e.g., buttons, headers, cards).
2. **Create Component-Specific CSS Files**: For each component, create a dedicated CSS file (e.g., `Button.module.css`).
3. **Import CSS Files into Components**: Import the component-specific CSS file into its respective React component.
   
   **Example**:
   - **Before (Global CSS)**:
     ```css
     /* styles.css */
     .button {
       padding: 10px;
       background-color: blue;
     }
     ```

   - **After (Modular CSS)**:
     - **Button.module.css**:
       ```css
       .button {
         padding: 10px;
         background-color: blue;
       }
       ```

     - **Button.js**:
       ```javascript
       import React from 'react';
       import styles from './Button.module.css';

       function Button() {
         return <button className={styles.button}>Click Me</button>;
       }

       export default Button;
       ```

### **Action Items**:
- Refactor existing global styles into modular CSS files.
- Update component imports to use the modular CSS files.
- Test that the styles are still applied correctly after the conversion.
